### PR TITLE
Enable instructor only announcement settings

### LINKED ISSUE #1: Feature Request: Classroom/Forum settings - Make Announcements Instructors Only
**User Story:** As a instructor, I only want other instructors to be able to post announcements so that students are not able to create an excess number of irrelevant posts in the announcement section.

**Estimated effort:** 20 Hours

**Dependencies:** None (will update if any)

**Initial assignments:** All team members work on this feature together (will update later)

**Milestones:** Sprint 1 (will update if changed)

**Acceptance criteria:**

- Teachers and admins can see a new button to toggle in their settings page.
- If teachers/admins enable such settings, students will no longer be able to post in announcement: either the new post button is invisible for the students, or students see a prompt error message when they try to make such post.
- Tests are added to check if the feature is implemented safely and correctly. E.g., students are not able to toggle the classroom settings.

### PR DESCRIPTION
**Pull request by FireACNC**
Partially solved issue #1 

**Current Progress:**
1. Instructors have a button in the settings page, which can toggle and update user's settings for enabling instructor only posts.
2. When a student tried to post an announcement, an error message will pop up and they won't be able to publish it.

**Screen Shots**
Screenshot 2024-02-12 at 9 08 17 AM

Screenshot 2024-02-12 at 11 15 02 AM

**Strength**
Students are not able to create an excess number of irrelevant posts in the announcement section.
**Weakness**
The current toggle button doesn't affect the actual functionality, so instructor can't disable this functionality

**Next Step**
We have stored an extra property in the category object, so the next step will be linking the user's setting to this property, then link this property to the actual forum setting functionality.
We will also add some tests to this new feature.

### CODE REVIEW

**Comment by FireACNC** [comment]
Some current tests are failing because we disabled students from posting announcements. We should implement the whole feature and then rerun the tests with the default forum settings as students are able to post announcements.

**Comment by FireACNC** [comment]
The feature is set to disabled by default to pass the tests. If you would like to try out the feature, set `const instructorOnlyAnnouncement = true;` in src/topics/create.js

**Review by 22zhuamanda — COMMENTED** [review]
lgtm

**Review by runxinz — APPROVED** [review]
This looks clean!

**Comment by wenchaohu1** [comment]
LGTM!

**Pull request merged**
