### PR TITLE
Automated Tests and Documentation for Instructor Only Announcements

### LINKED ISSUE #13: Instructor Only Announcement - Testing and Documentation
**User Story:** As a instructor, I only want other instructors to be able to post announcements so that students are not able to create an excess number of irrelevant posts in the announcement section.

**Estimated effort:** 10 Hours

**Dependencies:** Might need to wait for issue #12 to be solved

**Initial assignments:** Tiger

**Milestones:** Complete by the first week of Sprint 2 if dependencies are achieved.

**Acceptance criteria:**
Write automated tests that check for:
1. Teachers are able to toggle the settings; students are not able to do so
2. After enabling the setting, students can't post announcements
3. After enabling the setting, teachers can post announcements and students can still see them
4. After disabling the setting, teachers and students can both post announcements

### PR DESCRIPTION
**Pull request by FireACNC**
Solved issue #13; provided insights on #16 (Edit: to fully pass the test we solved #16 as well).

**Content added**: 
Some frontend-backend linkage; 
An automated tests that check if the new feature is working properly;
A user guide that covers the feature description, usage, user testing, and automated testing.

There are no front-end changes since pull request #3. No screenshots will be provided.

Ideally, the code coverage will go up after adding the test; However since this branch also inevitably touches on the frontend-backend linkage this is not guaranteed.

### CODE REVIEW

**Comment by FireACNC** [comment]
Several tests are failing; however note that all tests using redis database are indeed passing; We didn't learn how to perform local testing on different databases such as mongo and Postgres, so with the current knowledge we aren't able to fix it. We can mark this as an extended milestone to work on.

We also failed some i18n test locally, because our current changes only update EN languages files. This is also beyond the development scope right now.

**Comment by FireACNC** [comment]
Update: all tests passed now.

**Review by runxinz — COMMENTED** [review]
Looks good - code additions are easy to read and understand.

**Comment by gao-yuhan** [comment]
LGTM - tests exactly checked whether the instructor-only feature was successfully implemented. 
The code was also well-structured
Solved different databases issue

**Review by gao-yuhan — COMMENTED** [review]
LGTM - tests exactly checked whether the instructor-only feature was successfully implemented.
The code was also well-structured
Solved different databases issue

**Review by 22zhuamanda — COMMENTED** [review]
lgtm - new code is clean and easy to understand, tests are comprehensive and test the acceptance criteria of the issue

**Comment by wenchaohu1** [comment]
Looks good! The code is well-organized and easy to understand. The test cases cover that the feature is supposed to work as it should. Great work!

**Pull request merged**
